spring.datasource.url=jdbc:mariadb://games-db:3307/games
spring.datasource.username=cristina
spring.datasource.password=${GAMES_DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=ERROR
