spring.datasource.url=jdbc:mariadb://localhost:3307/games
spring.datasource.username=cristina
spring.datasource.password={cipher}cfe40b2f319e055c0ae19a5d3e7bbb3c6b322c109b0b9c62e4a99298cb826c88
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=DEBUG
