spring.datasource.url=jdbc:mariadb://localhost:3307/games
spring.datasource.username=games_user2
spring.datasource.password=games_password2
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=ERROR
